POST http://localhost:8000/api/signup/
Content-Type: application/json

{
  "username": "olive",
  "password": "Azertylilivier59!",
  "email": "electrikbox@icloud.com",
  "first_name": "olive",
  "last_name": "electrik"
}

###

POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "username": "electrik",
  "password": "olive"
}

###

POST http://localhost:8000/api/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcwOTk4Njg4OCwiaWF0IjoxNzA5OTAwNDg4LCJqdGkiOiJiNjQzNDIzNDNlMDU0ZWU2OGI5NGExYWZkZDc1NWRmMiIsInVzZXJfaWQiOjF9.SGkcMk254uxH0OoK4YvsivroXRavGnBufZBMLPAxTd8"
}

###

GET http://localhost:8000/api/crons/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5OTQ0MDU3LCJpYXQiOjE3MDk4NTc2NTcsImp0aSI6IjQ1ZmIzZjE5ZTIzNTQ1OWFhMDNiYjA5MmIyZTM1MmIzIiwidXNlcl9pZCI6MX0.BtqQKOxh3I3xHd0wrAEHsLTbN9A1d5-hQr-UH8wmlEk

{}

###

GET http://localhost:8000/api/crons/14/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5ODk1MzIxLCJpYXQiOjE3MDk4OTUyNjEsImp0aSI6Ijg0ZDE4Y2U0NGU4YTRiMmFhM2M3NTAwMTg4MzcxNmMzIiwidXNlcl9pZCI6MX0.5aW9aAUF6MsNFErOVJbE5vpgROGrDEnCSI2R3suoUvQ

{}

###

POST http://localhost:8000/api/crons/create/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5ODk1MzIxLCJpYXQiOjE3MDk4OTUyNjEsImp0aSI6Ijg0ZDE4Y2U0NGU4YTRiMmFhM2M3NTAwMTg4MzcxNmMzIiwidXNlcl9pZCI6MX0.5aW9aAUF6MsNFErOVJbE5vpgROGrDEnCSI2R3suoUvQ

{
  "minutes": "30",
  "hours": "10",
  "day_of_month": "24",
  "months": "dec",
  "day_of_week": "*",
  "command": "ls",
  "user": 1,
  "is_paused": false,
  "validated" : false
}

###

PUT http://localhost:8000/api/crons/14/update/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5ODk1MzIxLCJpYXQiOjE3MDk4OTUyNjEsImp0aSI6Ijg0ZDE4Y2U0NGU4YTRiMmFhM2M3NTAwMTg4MzcxNmMzIiwidXNlcl9pZCI6MX0.5aW9aAUF6MsNFErOVJbE5vpgROGrDEnCSI2R3suoUvQ

{
  "minutes": "*",
  "hours": "*",
  "day_of_month": "*",
  "months": "mar",
  "day_of_week": "mon",
  "command": "cal",
  "is_paused": true,
  "validated" : false
}

###

DELETE http://localhost:8000/api/crons/14/delete/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5ODk1NDAzLCJpYXQiOjE3MDk4OTUzNDMsImp0aSI6IjQ1NmViMjFkZmI1ZjRkN2NiN2VjZWUyYWNjNjM2YjliIiwidXNlcl9pZCI6MX0.eflvqnvB3MT3Bx8Z7T7krZTtuOUqirSUJs06zVn-z_M

{}
