POST http://localhost:8000/api/signup/
Content-Type: application/json

{
  "username": "olive",
  "password": "Azertylilivier59!",
  "email": "electrikbox@icloud.com",
  "first_name": "olive",
  "last_name": "electrik"
}

###

POST http://localhost:8000/api/login/
Content-Type: application/json

{
  "username": "electrik",
  "password": "olive"
}

###

GET http://localhost:8000/api/crons/
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzA5OTQ0MDU3LCJpYXQiOjE3MDk4NTc2NTcsImp0aSI6IjQ1ZmIzZjE5ZTIzNTQ1OWFhMDNiYjA5MmIyZTM1MmIzIiwidXNlcl9pZCI6MX0.BtqQKOxh3I3xHd0wrAEHsLTbN9A1d5-hQr-UH8wmlEk

{}

###

GET http://localhost:8000/api/crons/53/
Content-Type: application/json
Authorization: Token 073e46ad11d972448ff465765ff1f5bf44249495

{}

###

POST http://localhost:8000/api/crons/create/
Content-Type: application/json
Authorization: Token 6f2559adb4f3e4f02fc5197463b69e02e080897c

{
  "minutes": "30",
  "hours": "10",
  "day_of_month": "24",
  "months": "dec",
  "day_of_week": "*",
  "command": "ls",
  "user": 1,
  "is_paused": false,
  "validated" : false
}

###

PUT http://localhost:8000/api/crons/269/update/
Content-Type: application/json
Authorization: Token 073e46ad11d972448ff465765ff1f5bf44249495

{
  "minutes": "*",
  "hours": "*",
  "day_of_month": "*",
  "months": "mar",
  "day_of_week": "mon",
  "command": "pwd",
  "is_paused": true,
  "validated" : false
}

###

DELETE http://localhost:8000/api/crons/683/delete/
Content-Type: application/json
Authorization: Token 6863d9c35569d486310c3c706a306158e2a57dc9

{}
